export type FoodOptionMeal = "breakfast" | "lunch" | "dinner";

export type FoodOption = {
  name: string;
  mealType: FoodOptionMeal;
};

// Nitin's regular home-cooked rotation, shared by his health coach.
export const FOOD_OPTIONS: FoodOption[] = [
  // Lunch
  { name: "Chana Masala", mealType: "lunch" },
  { name: "Choley - Sindhi Style", mealType: "lunch" },
  { name: "Bhindi Fry", mealType: "lunch" },
  { name: "Bhindi 2 Pyaaza", mealType: "lunch" },
  { name: "Bhindi Masala", mealType: "lunch" },
  { name: "Baigan Bharta", mealType: "lunch" },
  { name: "Mushroom Masala", mealType: "lunch" },
  { name: "Mutter Paneer", mealType: "lunch" },
  { name: "Mutter Mushroom", mealType: "lunch" },
  { name: "Paneer Makhanwala", mealType: "lunch" },
  { name: "Paneer Masala", mealType: "lunch" },
  { name: "Ghee Roast Mushroom", mealType: "lunch" },
  { name: "Ghee Roast Paneer", mealType: "lunch" },
  { name: "Paneer Bhurji", mealType: "lunch" },
  { name: "Egg Bhurji", mealType: "lunch" },
  { name: "Tur Dali Dal", mealType: "lunch" },
  { name: "Black Dal - Makhani", mealType: "lunch" },
  { name: "Yellow Dal", mealType: "lunch" },
  { name: "Flower Gobhi", mealType: "lunch" },
  { name: "Patta Gobi", mealType: "lunch" },
  { name: "Egg Curry / Masala", mealType: "lunch" },
  { name: "Mix Veg", mealType: "lunch" },
  { name: "Chawli", mealType: "lunch" },
  { name: "Rajma", mealType: "lunch" },
  { name: "Watana (Mix Pulses)", mealType: "lunch" },
  { name: "Masala Baigan Fry", mealType: "lunch" },
  { name: "Kaju Curry", mealType: "lunch" },
  { name: "Malai Methi Mutter", mealType: "lunch" },
  { name: "Veg Mumtaaz", mealType: "lunch" },

  // Breakfast
  { name: "Ragi Dosa", mealType: "breakfast" },
  { name: "Ragi Utappam", mealType: "breakfast" },
  { name: "Multi Grain Dosa", mealType: "breakfast" },
  { name: "Podi Idli", mealType: "breakfast" },
  { name: "Podi Medu Vada", mealType: "breakfast" },
  { name: "Medu Vada", mealType: "breakfast" },
  { name: "Idli", mealType: "breakfast" },
  { name: "Podi Upma", mealType: "breakfast" },
  { name: "Gobi Paratha", mealType: "breakfast" },
  { name: "Paneer Paratha", mealType: "breakfast" },
  { name: "French Toast", mealType: "breakfast" },
  { name: "Egg Bhurji & Bread", mealType: "breakfast" },
  { name: "Spanish Omlette", mealType: "breakfast" },
  { name: "Spinach Omlette", mealType: "breakfast" },
  { name: "Mutter Paratha", mealType: "breakfast" },
  { name: "Koki", mealType: "breakfast" },
  { name: "Thepla", mealType: "breakfast" },
  { name: "Pata Ghobi Paratha", mealType: "breakfast" },
  { name: "Muli Paratha", mealType: "breakfast" },
  { name: "Mix Veg Paratha", mealType: "breakfast" },
  { name: "Upma", mealType: "breakfast" },
  { name: "Poha", mealType: "breakfast" },
  { name: "Suji Chila", mealType: "breakfast" },
  { name: "Paniyaram", mealType: "breakfast" },
  { name: "Moong Dal Chila", mealType: "breakfast" },
  { name: "Dal Paati", mealType: "breakfast" },
  { name: "Besan Chila", mealType: "breakfast" },
  { name: "Rava Dosa", mealType: "breakfast" },
  { name: "Uttapam", mealType: "breakfast" },
  { name: "Dosa - Ragi", mealType: "breakfast" },
  { name: "Dosa - Normal", mealType: "breakfast" },
  { name: "Mutter Chura", mealType: "breakfast" },
  { name: "Pata Gobi Paratha", mealType: "breakfast" },
  { name: "Moong Paratha", mealType: "breakfast" },
  { name: "Palak Cheela", mealType: "breakfast" },
  { name: "Palak Paneer Cheela", mealType: "breakfast" },
  { name: "Palak Paratha", mealType: "breakfast" },
  { name: "Carrot Dosa", mealType: "breakfast" },
  { name: "Thalipeeth", mealType: "breakfast" },
  { name: "Misal Pav", mealType: "breakfast" },

  // Dinner
  { name: "Tomato Rice", mealType: "dinner" },
  { name: "Dal Rice", mealType: "dinner" },
  { name: "Dal Khicdhi", mealType: "dinner" },
  { name: "Curd Rice", mealType: "dinner" },
  { name: "Coconut Rice", mealType: "dinner" },
  { name: "Mushroom Rice", mealType: "dinner" },
  { name: "Schezwan Rice", mealType: "dinner" },
  { name: "Burnt Garlic Rice", mealType: "dinner" },
  { name: "Salad", mealType: "dinner" },
  { name: "Dahi Curry Rice", mealType: "dinner" },
  { name: "Rassam Rice", mealType: "dinner" },
  { name: "Sambhar Rice", mealType: "dinner" },
  { name: "Pulav", mealType: "dinner" },
  { name: "Lemon Rice", mealType: "dinner" },
  { name: "Fried Rice", mealType: "dinner" },
  { name: "Butter Chicken", mealType: "dinner" },
  { name: "Whole Wheat Burger", mealType: "dinner" },
  { name: "Whole Wheat Pizza", mealType: "dinner" },
  { name: "Whole Wheat Pasta", mealType: "dinner" },
  { name: "Whole Wheat Sandwich (Egg)", mealType: "dinner" },
  { name: "Whole Wheat Sandwich (Veg)", mealType: "dinner" },
  { name: "Spinach Rice + Paprika", mealType: "dinner" },
  { name: "Rajma + Rice", mealType: "dinner" },
  { name: "Mushroom Rissoto", mealType: "dinner" },
  { name: "Spanish Rice", mealType: "dinner" },
  { name: "Thai Curry - Rice (Green)", mealType: "dinner" },
  { name: "Thai Curry - Rice (Red)", mealType: "dinner" },
  { name: "Stew + Rice", mealType: "dinner" },
  { name: "Spinach Rice With Paprika Sauce", mealType: "dinner" },
  { name: "Nasi Goreng", mealType: "dinner" },
  { name: "Khow Suey", mealType: "dinner" },
];
